/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.pkgcase.management;

/**
 *
 * @author vish
 */
public class Visits extends javax.swing.JFrame {

    /**
     * Creates new form Visits
     */
    public Visits() {
        initComponents();
                setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        visitDateLabel = new javax.swing.JLabel();
        visitDatePicker = new org.jdesktop.swingx.JXDatePicker();
        chiefComplaintLabel = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        chiefComplaintInput = new javax.swing.JTextArea();
        originLabel = new javax.swing.JLabel();
        jScrollPane33 = new javax.swing.JScrollPane();
        originInput = new javax.swing.JTextArea();
        durationLabel = new javax.swing.JLabel();
        jScrollPane34 = new javax.swing.JScrollPane();
        durationInput = new javax.swing.JTextArea();
        progressLabel = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        progressInput = new javax.swing.JTextArea();
        habitLabel = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        habitInput = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        appetiteLabel = new javax.swing.JLabel();
        thirstLabel = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        thirstInput = new javax.swing.JTextArea();
        desireLabel = new javax.swing.JLabel();
        jScrollPane20 = new javax.swing.JScrollPane();
        desireInput = new javax.swing.JTextArea();
        aversionLabel = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        aversionInput = new javax.swing.JTextArea();
        stoolLabel = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        stoolInput = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        urineInput = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        appetiteInput = new javax.swing.JTextArea();
        urineLabel = new javax.swing.JLabel();
        perspirationLabel = new javax.swing.JLabel();
        sleepLabel = new javax.swing.JLabel();
        dreamsLabel = new javax.swing.JLabel();
        thermallyLabel = new javax.swing.JLabel();
        gynacHistoryLabel1 = new javax.swing.JLabel();
        mindLabel1 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        perspirationInput = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        sleepInput = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        dreamsInput = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        thermallyInput1 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        gynacHistoryInput = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        mindInput = new javax.swing.JTextArea();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(208, 43));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(211, 50));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Visits"));

        visitDateLabel.setText("Visit Date");

        chiefComplaintLabel.setText("Chief Complaint");

        chiefComplaintInput.setColumns(20);
        chiefComplaintInput.setLineWrap(true);
        chiefComplaintInput.setRows(5);
        jScrollPane32.setViewportView(chiefComplaintInput);

        originLabel.setText("Origin");

        originInput.setColumns(20);
        originInput.setLineWrap(true);
        originInput.setRows(5);
        jScrollPane33.setViewportView(originInput);

        durationLabel.setText("Duration");

        durationInput.setColumns(20);
        durationInput.setLineWrap(true);
        durationInput.setRows(5);
        jScrollPane34.setViewportView(durationInput);

        progressLabel.setText("Progress");

        progressInput.setColumns(20);
        progressInput.setLineWrap(true);
        progressInput.setRows(5);
        jScrollPane35.setViewportView(progressInput);

        habitLabel.setText("Habit/Addiction");

        habitInput.setColumns(20);
        habitInput.setLineWrap(true);
        habitInput.setRows(5);
        jScrollPane36.setViewportView(habitInput);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(visitDateLabel)
                        .addGap(44, 44, 44)
                        .addComponent(visitDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(originLabel)
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(habitLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(progressLabel, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addComponent(durationLabel))
                            .addComponent(chiefComplaintLabel))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane32, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(visitDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitDateLabel))
                .addGap(33, 33, 33)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(chiefComplaintLabel)))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(originLabel))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progressLabel)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habitLabel)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jScrollPane31.setViewportView(jPanel13);

        jTabbedPane1.addTab("Visit Details", jScrollPane31);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Generals"));

        appetiteLabel.setText("Appetite");

        thirstLabel.setText("Thirst");

        thirstInput.setColumns(20);
        thirstInput.setLineWrap(true);
        thirstInput.setRows(5);
        jScrollPane19.setViewportView(thirstInput);

        desireLabel.setText("Desire");

        desireInput.setColumns(20);
        desireInput.setLineWrap(true);
        desireInput.setRows(5);
        jScrollPane20.setViewportView(desireInput);

        aversionLabel.setText("Aversion");

        aversionInput.setColumns(20);
        aversionInput.setLineWrap(true);
        aversionInput.setRows(5);
        jScrollPane21.setViewportView(aversionInput);

        stoolLabel.setText("Stool");

        stoolInput.setColumns(20);
        stoolInput.setLineWrap(true);
        stoolInput.setRows(5);
        jScrollPane22.setViewportView(stoolInput);

        urineInput.setColumns(20);
        urineInput.setLineWrap(true);
        urineInput.setRows(5);
        jScrollPane23.setViewportView(urineInput);

        appetiteInput.setColumns(20);
        appetiteInput.setLineWrap(true);
        appetiteInput.setRows(5);
        jScrollPane24.setViewportView(appetiteInput);

        urineLabel.setText("Urine");

        perspirationLabel.setText("Perspiration");

        sleepLabel.setText("Sleep");

        dreamsLabel.setText("Dreams");

        thermallyLabel.setText("Thermally");

        gynacHistoryLabel1.setText("Gynac History");

        mindLabel1.setText("Mind");

        perspirationInput.setColumns(20);
        perspirationInput.setLineWrap(true);
        perspirationInput.setRows(5);
        jScrollPane25.setViewportView(perspirationInput);

        sleepInput.setColumns(20);
        sleepInput.setLineWrap(true);
        sleepInput.setRows(5);
        jScrollPane26.setViewportView(sleepInput);

        dreamsInput.setColumns(20);
        dreamsInput.setLineWrap(true);
        dreamsInput.setRows(5);
        jScrollPane27.setViewportView(dreamsInput);

        thermallyInput1.setColumns(20);
        thermallyInput1.setLineWrap(true);
        thermallyInput1.setRows(5);
        jScrollPane28.setViewportView(thermallyInput1);

        gynacHistoryInput.setColumns(20);
        gynacHistoryInput.setLineWrap(true);
        gynacHistoryInput.setRows(5);
        jScrollPane29.setViewportView(gynacHistoryInput);

        mindInput.setColumns(20);
        mindInput.setLineWrap(true);
        mindInput.setRows(5);
        jScrollPane30.setViewportView(mindInput);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appetiteLabel)
                    .addComponent(thirstLabel)
                    .addComponent(desireLabel)
                    .addComponent(aversionLabel)
                    .addComponent(stoolLabel)
                    .addComponent(urineLabel)
                    .addComponent(mindLabel1)
                    .addComponent(gynacHistoryLabel1)
                    .addComponent(thermallyLabel)
                    .addComponent(dreamsLabel)
                    .addComponent(sleepLabel)
                    .addComponent(perspirationLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane20, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane21, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane22, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane23, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                    .addComponent(jScrollPane24)
                    .addComponent(jScrollPane25)
                    .addComponent(jScrollPane26)
                    .addComponent(jScrollPane27)
                    .addComponent(jScrollPane28)
                    .addComponent(jScrollPane29)
                    .addComponent(jScrollPane30))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(appetiteLabel)
                        .addGap(37, 37, 37)
                        .addComponent(thirstLabel)
                        .addGap(36, 36, 36)
                        .addComponent(desireLabel)
                        .addGap(37, 37, 37)
                        .addComponent(aversionLabel)
                        .addGap(38, 38, 38)
                        .addComponent(stoolLabel)
                        .addGap(37, 37, 37)
                        .addComponent(urineLabel)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(perspirationLabel)
                        .addGap(37, 37, 37)
                        .addComponent(sleepLabel)
                        .addGap(37, 37, 37)
                        .addComponent(dreamsLabel))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(thermallyLabel)
                        .addGap(38, 38, 38)
                        .addComponent(gynacHistoryLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(mindLabel1))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane18.setViewportView(jPanel12);

        jTabbedPane1.addTab("Physical Details", jScrollPane18);

        saveButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.setActionCommand("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visits().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea appetiteInput;
    private javax.swing.JLabel appetiteLabel;
    private javax.swing.JTextArea aversionInput;
    private javax.swing.JLabel aversionLabel;
    private javax.swing.JTextArea chiefComplaintInput;
    private javax.swing.JLabel chiefComplaintLabel;
    private javax.swing.JTextArea desireInput;
    private javax.swing.JLabel desireLabel;
    private javax.swing.JTextArea dreamsInput;
    private javax.swing.JLabel dreamsLabel;
    private javax.swing.JTextArea durationInput;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextArea gynacHistoryInput;
    private javax.swing.JLabel gynacHistoryLabel1;
    private javax.swing.JTextArea habitInput;
    private javax.swing.JLabel habitLabel;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea mindInput;
    private javax.swing.JLabel mindLabel1;
    private javax.swing.JTextArea originInput;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextArea perspirationInput;
    private javax.swing.JLabel perspirationLabel;
    private javax.swing.JTextArea progressInput;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea sleepInput;
    private javax.swing.JLabel sleepLabel;
    private javax.swing.JTextArea stoolInput;
    private javax.swing.JLabel stoolLabel;
    private javax.swing.JTextArea thermallyInput1;
    private javax.swing.JLabel thermallyLabel;
    private javax.swing.JTextArea thirstInput;
    private javax.swing.JLabel thirstLabel;
    private javax.swing.JTextArea urineInput;
    private javax.swing.JLabel urineLabel;
    private javax.swing.JLabel visitDateLabel;
    private org.jdesktop.swingx.JXDatePicker visitDatePicker;
    // End of variables declaration//GEN-END:variables
}
