/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medical.pkgcase.management;

import java.io.File;
import static java.lang.ProcessBuilder.Redirect.from;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author vish
 */
public class Visits extends javax.swing.JFrame {

    /**
     * Creates new form Visits
     */
    public Visits() {
        initComponents();
        
        String visitID = "";
                fileChooser.setAcceptAllFileFilterUsed(false);
        FileNameExtensionFilter jpgfilter = new FileNameExtensionFilter("JPEG Files", "jpg");
        FileNameExtensionFilter pngfilter = new FileNameExtensionFilter("PNG Files", "png");
               


        fileChooser.addChoosableFileFilter(jpgfilter);
                fileChooser.addChoosableFileFilter(pngfilter);

                setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        jPanel13 = new javax.swing.JPanel();
        chiefComplaintLabel = new javax.swing.JLabel();
        jScrollPane32 = new javax.swing.JScrollPane();
        chiefComplaintInput = new javax.swing.JTextArea();
        originLabel = new javax.swing.JLabel();
        jScrollPane33 = new javax.swing.JScrollPane();
        originInput = new javax.swing.JTextArea();
        durationLabel = new javax.swing.JLabel();
        jScrollPane34 = new javax.swing.JScrollPane();
        durationInput = new javax.swing.JTextArea();
        progressLabel = new javax.swing.JLabel();
        jScrollPane35 = new javax.swing.JScrollPane();
        progressInput = new javax.swing.JTextArea();
        habitLabel = new javax.swing.JLabel();
        jScrollPane36 = new javax.swing.JScrollPane();
        habitInput = new javax.swing.JTextArea();
        jScrollPane18 = new javax.swing.JScrollPane();
        jPanel12 = new javax.swing.JPanel();
        appetiteLabel = new javax.swing.JLabel();
        thirstLabel = new javax.swing.JLabel();
        likeLabel = new javax.swing.JLabel();
        aversionLabel = new javax.swing.JLabel();
        jScrollPane21 = new javax.swing.JScrollPane();
        aversionInput = new javax.swing.JTextArea();
        stoolLabel = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        stoolInput = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        appetiteInput = new javax.swing.JTextArea();
        urineLabel = new javax.swing.JLabel();
        perspirationLabel = new javax.swing.JLabel();
        sleepLabel = new javax.swing.JLabel();
        dreamsLabel = new javax.swing.JLabel();
        thermallyLabel = new javax.swing.JLabel();
        gynacHistoryLabel1 = new javax.swing.JLabel();
        mindLabel1 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        perspirationInput = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        sleepInput = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        dreamsInput = new javax.swing.JTextArea();
        jScrollPane28 = new javax.swing.JScrollPane();
        thermallyInput1 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        gynacHistoryInput = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        mindInput = new javax.swing.JTextArea();
        likeComboBox = new javax.swing.JComboBox<>();
        urineComboBox = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        thirstInput = new javax.swing.JTextArea();
        extraLikesInput = new javax.swing.JTextField();
        extraUrineInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pePanel = new javax.swing.JPanel();
        generalTitleLabel = new javax.swing.JLabel();
        temperatureLabel = new javax.swing.JLabel();
        pulseInput = new javax.swing.JTextField();
        pulseLabel = new javax.swing.JLabel();
        temperatureInput = new javax.swing.JTextField();
        respiratoryRateInput = new javax.swing.JTextField();
        respiratoryRateLabel = new javax.swing.JLabel();
        othersInput = new javax.swing.JScrollPane();
        otherInput = new javax.swing.JTextArea();
        othersLabel = new javax.swing.JLabel();
        vitalTitleLabel = new javax.swing.JLabel();
        cvsLabel = new javax.swing.JLabel();
        cvsInput = new javax.swing.JTextField();
        rsLabel = new javax.swing.JLabel();
        rsInput = new javax.swing.JTextField();
        cnsLabel = new javax.swing.JLabel();
        cnsInput = new javax.swing.JTextField();
        paLabel = new javax.swing.JLabel();
        paInput = new javax.swing.JScrollPane();
        pAInput = new javax.swing.JTextArea();
        invgLabel = new javax.swing.JLabel();
        invgInput = new javax.swing.JTextField();
        miasmLabel = new javax.swing.JLabel();
        miasmInput = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        diagPanel = new javax.swing.JPanel();
        susceptibilityLabel = new javax.swing.JLabel();
        susceptibulityInput = new javax.swing.JScrollPane();
        susceptibilityInput = new javax.swing.JTextArea();
        finalDiagnosisLabel = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        finalDiagnosisInput = new javax.swing.JTextArea();
        probableRemediesLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        probableRemediesInput = new javax.swing.JTextArea();
        fileChooser = new javax.swing.JFileChooser();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(208, 43));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(211, 50));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Visits"));

        chiefComplaintLabel.setText("Chief Complaint");

        chiefComplaintInput.setColumns(20);
        chiefComplaintInput.setLineWrap(true);
        chiefComplaintInput.setRows(5);
        jScrollPane32.setViewportView(chiefComplaintInput);

        originLabel.setText("Origin");

        originInput.setColumns(20);
        originInput.setLineWrap(true);
        originInput.setRows(5);
        jScrollPane33.setViewportView(originInput);

        durationLabel.setText("Duration");

        durationInput.setColumns(20);
        durationInput.setLineWrap(true);
        durationInput.setRows(5);
        jScrollPane34.setViewportView(durationInput);

        progressLabel.setText("Progress");

        progressInput.setColumns(20);
        progressInput.setLineWrap(true);
        progressInput.setRows(5);
        jScrollPane35.setViewportView(progressInput);

        habitLabel.setText("Habit/Addiction");

        habitInput.setColumns(20);
        habitInput.setLineWrap(true);
        habitInput.setRows(5);
        jScrollPane36.setViewportView(habitInput);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(durationLabel)
                                    .addComponent(progressLabel)
                                    .addComponent(originLabel))
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(habitLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane35, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(jScrollPane34, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
                            .addComponent(jScrollPane36, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(chiefComplaintLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane32, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel13Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane33, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chiefComplaintLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(originLabel)
                    .addComponent(jScrollPane33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(durationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progressLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habitLabel))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jScrollPane31.setViewportView(jPanel13);

        jTabbedPane1.addTab("Visit Details", jScrollPane31);

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Generals"));

        appetiteLabel.setText("Appetite");

        thirstLabel.setText("Thirst");

        likeLabel.setText("Likes");

        aversionLabel.setText("Aversion");

        aversionInput.setColumns(20);
        aversionInput.setLineWrap(true);
        aversionInput.setRows(5);
        jScrollPane21.setViewportView(aversionInput);

        stoolLabel.setText("Stool");

        stoolInput.setColumns(20);
        stoolInput.setLineWrap(true);
        stoolInput.setRows(5);
        jScrollPane22.setViewportView(stoolInput);

        appetiteInput.setColumns(20);
        appetiteInput.setLineWrap(true);
        appetiteInput.setRows(5);
        jScrollPane24.setViewportView(appetiteInput);

        urineLabel.setText("Urine");

        perspirationLabel.setText("Perspiration");

        sleepLabel.setText("Sleep");

        dreamsLabel.setText("Dreams");

        thermallyLabel.setText("Thermally");

        gynacHistoryLabel1.setText("Gynac History");

        mindLabel1.setText("Mind");

        perspirationInput.setColumns(20);
        perspirationInput.setLineWrap(true);
        perspirationInput.setRows(5);
        jScrollPane25.setViewportView(perspirationInput);

        sleepInput.setColumns(20);
        sleepInput.setLineWrap(true);
        sleepInput.setRows(5);
        jScrollPane26.setViewportView(sleepInput);

        dreamsInput.setColumns(20);
        dreamsInput.setLineWrap(true);
        dreamsInput.setRows(5);
        jScrollPane27.setViewportView(dreamsInput);

        thermallyInput1.setColumns(20);
        thermallyInput1.setLineWrap(true);
        thermallyInput1.setRows(5);
        jScrollPane28.setViewportView(thermallyInput1);

        gynacHistoryInput.setColumns(20);
        gynacHistoryInput.setLineWrap(true);
        gynacHistoryInput.setRows(5);
        jScrollPane29.setViewportView(gynacHistoryInput);

        mindInput.setColumns(20);
        mindInput.setLineWrap(true);
        mindInput.setRows(5);
        jScrollPane30.setViewportView(mindInput);

        likeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sweet", "Salty", "Sour", "Bitter", "Spicy" }));

        urineComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excessive", "Higher than normal", "Normal", "Slightly less than normal", "Dangerously low" }));

        thirstInput.setColumns(20);
        thirstInput.setRows(5);
        jScrollPane4.setViewportView(thirstInput);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(appetiteLabel)
                    .addComponent(thirstLabel)
                    .addComponent(likeLabel)
                    .addComponent(aversionLabel)
                    .addComponent(stoolLabel)
                    .addComponent(urineLabel)
                    .addComponent(mindLabel1)
                    .addComponent(gynacHistoryLabel1)
                    .addComponent(thermallyLabel)
                    .addComponent(dreamsLabel)
                    .addComponent(sleepLabel)
                    .addComponent(perspirationLabel))
                .addGap(26, 26, 26)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane21)
                    .addComponent(jScrollPane22)
                    .addComponent(jScrollPane24)
                    .addComponent(jScrollPane25)
                    .addComponent(jScrollPane26)
                    .addComponent(jScrollPane27)
                    .addComponent(jScrollPane28)
                    .addComponent(jScrollPane29)
                    .addComponent(jScrollPane30)
                    .addComponent(jScrollPane4)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(likeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(extraLikesInput, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(urineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(extraUrineInput, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane24, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(likeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraLikesInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(urineComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(extraUrineInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(appetiteLabel)
                        .addGap(37, 37, 37)
                        .addComponent(thirstLabel)
                        .addGap(36, 36, 36)
                        .addComponent(likeLabel)
                        .addGap(37, 37, 37)
                        .addComponent(aversionLabel)
                        .addGap(38, 38, 38)
                        .addComponent(stoolLabel)
                        .addGap(37, 37, 37)
                        .addComponent(urineLabel)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(perspirationLabel)
                        .addGap(37, 37, 37)
                        .addComponent(sleepLabel)
                        .addGap(37, 37, 37)
                        .addComponent(dreamsLabel))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane25, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane26, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane27, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(thermallyLabel)
                        .addGap(38, 38, 38)
                        .addComponent(gynacHistoryLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(mindLabel1))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane29, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane30, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane18.setViewportView(jPanel12);

        jTabbedPane1.addTab("Physical Details", jScrollPane18);

        pePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Physical Examination"));

        generalTitleLabel.setText("General -");

        temperatureLabel.setText("Temperature");

        pulseInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pulseInputActionPerformed(evt);
            }
        });

        pulseLabel.setText("Pulse");

        temperatureInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureInputActionPerformed(evt);
            }
        });

        respiratoryRateLabel.setText("Respiratory Rate");

        otherInput.setColumns(20);
        otherInput.setLineWrap(true);
        otherInput.setRows(5);
        othersInput.setViewportView(otherInput);

        othersLabel.setText("Others");

        vitalTitleLabel.setText("Systemic with vital data - ");

        cvsLabel.setText("CVS");

        cvsInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvsInputActionPerformed(evt);
            }
        });

        rsLabel.setText("RS");

        cnsLabel.setText("CNS");

        paLabel.setText("P/A");

        pAInput.setColumns(20);
        pAInput.setLineWrap(true);
        pAInput.setRows(5);
        paInput.setViewportView(pAInput);

        invgLabel.setText("INVG Assigned");

        miasmLabel.setText("Miasm");

        javax.swing.GroupLayout pePanelLayout = new javax.swing.GroupLayout(pePanel);
        pePanel.setLayout(pePanelLayout);
        pePanelLayout.setHorizontalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pePanelLayout.createSequentialGroup()
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generalTitleLabel)
                            .addComponent(vitalTitleLabel)))
                    .addGroup(pePanelLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(temperatureLabel)
                            .addComponent(pulseLabel)
                            .addComponent(respiratoryRateLabel)
                            .addComponent(othersLabel)
                            .addGroup(pePanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rsLabel)
                                    .addComponent(cvsLabel)
                                    .addComponent(cnsLabel)
                                    .addComponent(paLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(invgLabel)
                                    .addComponent(miasmLabel))))
                        .addGap(18, 18, 18)
                        .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(othersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(respiratoryRateInput, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(pulseInput)
                                .addComponent(temperatureInput))
                            .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(rsInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cvsInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                                .addComponent(cnsInput))
                            .addComponent(paInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(miasmInput, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(invgInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        pePanelLayout.setVerticalGroup(
            pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(generalTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(temperatureLabel)
                    .addComponent(temperatureInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pulseInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(respiratoryRateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(respiratoryRateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(othersInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(othersLabel))
                .addGap(21, 21, 21)
                .addComponent(vitalTitleLabel)
                .addGap(26, 26, 26)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvsLabel)
                    .addComponent(cvsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rsLabel)
                    .addComponent(rsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cnsInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnsLabel))
                .addGap(4, 4, 4)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paLabel))
                .addGap(7, 7, 7)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invgLabel)
                    .addComponent(invgInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(miasmLabel)
                    .addComponent(miasmInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(pePanel);

        jTabbedPane1.addTab("Physical Examination", jScrollPane1);

        diagPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Diagnosis/Remedies"));

        susceptibilityLabel.setText("Susceptibility");

        susceptibilityInput.setColumns(20);
        susceptibilityInput.setLineWrap(true);
        susceptibilityInput.setRows(5);
        susceptibulityInput.setViewportView(susceptibilityInput);

        finalDiagnosisLabel.setText("Final Diagnosis");

        finalDiagnosisInput.setColumns(20);
        finalDiagnosisInput.setLineWrap(true);
        finalDiagnosisInput.setRows(5);
        jScrollPane.setViewportView(finalDiagnosisInput);

        probableRemediesLabel.setText("Probable Remedies");

        probableRemediesInput.setColumns(20);
        probableRemediesInput.setLineWrap(true);
        probableRemediesInput.setRows(5);
        jScrollPane3.setViewportView(probableRemediesInput);

        javax.swing.GroupLayout diagPanelLayout = new javax.swing.GroupLayout(diagPanel);
        diagPanel.setLayout(diagPanelLayout);
        diagPanelLayout.setHorizontalGroup(
            diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(susceptibilityLabel)
                        .addComponent(finalDiagnosisLabel))
                    .addComponent(probableRemediesLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(susceptibulityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );
        diagPanelLayout.setVerticalGroup(
            diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diagPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(susceptibulityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(susceptibilityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(finalDiagnosisLabel))
                .addGap(9, 9, 9)
                .addGroup(diagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(probableRemediesLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(504, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(diagPanel);

        jTabbedPane1.addTab("Diagnosis/Remedies", jScrollPane2);

        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });
        jTabbedPane1.addTab("Save Diagnosis", fileChooser);

        saveButton.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        saveButton.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pulseInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pulseInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pulseInputActionPerformed

    private void temperatureInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_temperatureInputActionPerformed

    private void cvsInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvsInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvsInputActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
        // TODO add your handling code here:
  if (evt.getActionCommand().equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
        File theDir = new File("Diagnosis Storage Folder/"+File.separator+patientID+File.separator+visitID);
        //File visitDir = new File(theDir + "/" + visitID);// Defining Directory/Folder Name  
    try{   
        if (!theDir.exists()){  // Checks that Directory/Folder Doesn't Exists!  
         boolean result = theDir.mkdirs();    
        }  
    }catch(Exception e){  
        JOptionPane.showMessageDialog(null, e);  
    }  
         counter++;        
       
         
         
         JOptionPane.showMessageDialog(null, "File number " + counter + " saved");
         String path = fileChooser.getSelectedFile().getAbsolutePath();
         JOptionPane.showMessageDialog(null, path);
         
         File src = new File(path);
        File target = new File(theDir.getAbsolutePath()+File.separator+counter);

        try
        {
        Files.copy(src.toPath(), target.toPath(), StandardCopyOption.REPLACE_EXISTING);
        }
        catch(Exception e)
        {}
                 

        
    } else if (evt.getActionCommand().equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
    }
    
  
    }//GEN-LAST:event_fileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visits.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visits().setVisible(true);
            }
        });
    }

    public int counter = 0;
    String patientID = "123123";
    String visitID = "CXZ";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea appetiteInput;
    private javax.swing.JLabel appetiteLabel;
    private javax.swing.JTextArea aversionInput;
    private javax.swing.JLabel aversionLabel;
    private javax.swing.JTextArea chiefComplaintInput;
    private javax.swing.JLabel chiefComplaintLabel;
    private javax.swing.JTextField cnsInput;
    private javax.swing.JLabel cnsLabel;
    private javax.swing.JTextField cvsInput;
    private javax.swing.JLabel cvsLabel;
    private javax.swing.JPanel diagPanel;
    private javax.swing.JTextArea dreamsInput;
    private javax.swing.JLabel dreamsLabel;
    private javax.swing.JTextArea durationInput;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JTextField extraLikesInput;
    private javax.swing.JTextField extraUrineInput;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextArea finalDiagnosisInput;
    private javax.swing.JLabel finalDiagnosisLabel;
    private javax.swing.JLabel generalTitleLabel;
    private javax.swing.JTextArea gynacHistoryInput;
    private javax.swing.JLabel gynacHistoryLabel1;
    private javax.swing.JTextArea habitInput;
    private javax.swing.JLabel habitLabel;
    private javax.swing.JTextField invgInput;
    private javax.swing.JLabel invgLabel;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> likeComboBox;
    private javax.swing.JLabel likeLabel;
    private javax.swing.JTextField miasmInput;
    private javax.swing.JLabel miasmLabel;
    private javax.swing.JTextArea mindInput;
    private javax.swing.JLabel mindLabel1;
    private javax.swing.JTextArea originInput;
    private javax.swing.JLabel originLabel;
    private javax.swing.JTextArea otherInput;
    private javax.swing.JScrollPane othersInput;
    private javax.swing.JLabel othersLabel;
    private javax.swing.JTextArea pAInput;
    private javax.swing.JScrollPane paInput;
    private javax.swing.JLabel paLabel;
    private javax.swing.JPanel pePanel;
    private javax.swing.JTextArea perspirationInput;
    private javax.swing.JLabel perspirationLabel;
    private javax.swing.JTextArea probableRemediesInput;
    private javax.swing.JLabel probableRemediesLabel;
    private javax.swing.JTextArea progressInput;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JTextField pulseInput;
    private javax.swing.JLabel pulseLabel;
    private javax.swing.JTextField respiratoryRateInput;
    private javax.swing.JLabel respiratoryRateLabel;
    private javax.swing.JTextField rsInput;
    private javax.swing.JLabel rsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextArea sleepInput;
    private javax.swing.JLabel sleepLabel;
    private javax.swing.JTextArea stoolInput;
    private javax.swing.JLabel stoolLabel;
    private javax.swing.JTextArea susceptibilityInput;
    private javax.swing.JLabel susceptibilityLabel;
    private javax.swing.JScrollPane susceptibulityInput;
    private javax.swing.JTextField temperatureInput;
    private javax.swing.JLabel temperatureLabel;
    private javax.swing.JTextArea thermallyInput1;
    private javax.swing.JLabel thermallyLabel;
    private javax.swing.JTextArea thirstInput;
    private javax.swing.JLabel thirstLabel;
    private javax.swing.JComboBox<String> urineComboBox;
    private javax.swing.JLabel urineLabel;
    private javax.swing.JLabel vitalTitleLabel;
    // End of variables declaration//GEN-END:variables
}
